# Generated by Django 2.2.9 on 2020-01-14 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendedor', models.CharField(max_length=50)),
                ('producido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('observacion', models.CharField(default='SIN OBSERVACION', max_length=500)),
                ('inversor', models.CharField(default='SIN INVERSOR', max_length=150)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldo_cuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_cuota', models.DateField()),
                ('mes_cuota', models.DateField()),
                ('anio_cuota', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credito.Credito')),
            ],
        ),
    ]
